apiVersion: v1
kind: Secret
metadata:
  name: homelab-infra
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/yoanbaulande/homelab-infra.git
