apiVersion: v1
kind: Service
metadata:
  name: wealthfolio
  namespace: wealthfolio
spec:
  type: NodePort
  selector:
    app: wealthfolio
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      nodePort: 32002
